### ISSUE TITLE
Dependencies support 

### ISSUE THREAD

**Issue by luis-07** [luis-07/gpac#1]
Support for dependencies.

**Comment by luis-07** [comment]
This can be done in the .conf file

**Comment by luis-07** [comment]
give me 2 days and they are impemented

**Comment by luis-07** [comment]
Not high on my list because i don`t have a concept for it

**Comment by Moritz448** [comment]
It´s integrated with the "I recommend installing dmenu" message, not?

**Comment by luis-07** [comment]
No

**Comment by luis-07** [comment]
That’s just a way of telling the user to do stuff

**Comment by Moritz448** [comment]
But you said you don´t want it

**Comment by luis-07** [comment]
not at the moment but in the future

**Comment by luis-07** [comment]
keep the issue open

**Comment by luis-07** [comment]
I have a working build locally i just have to test it more then i`ll push

**Comment by luis-07** [comment]
DONE!!!!!!!!!!
