### ISSUE TITLE
Got this stupid error

### ISSUE THREAD

**Issue by Moritz448** [luis-07/gpac#10]
`moritz@pop-os:~/Dokumente/gpac$ sudo gpac b doas`
`installing package: doas`
` ✅   Using repo at: /home/glenda/g/gpac/repo/`
` ❌ Package doas not found `
`moritz@pop-os:~/Dokumente/gpac$ `

**Comment by luis-07** [comment]
sudo nano /etc/gpac.gconf 
Change /home/glenda... to /home/moritz/Dokumente/gpac/repo/

**Comment by Moritz448** [comment]
@luis-07 Did you changed the way of handling repos? Also happening with other packages.

**Comment by luis-07** [comment]
Do what I said it will fix it

**Comment by luis-07** [comment]
I don’t have time at the moment but today a new repo system will be implemented

**Comment by Moritz448** [comment]
Now this happens:

moritz@pop-os:~$ sudo gpac b doas
installing package: doas
 ✅   Using repo at: /home/moritz/Dokumente/gpac/repo/
 ✅   Package doas found
 ✅   Creating tmpdir: /tmp/doas
https://raw.githubusercontent.com/luis-07/tar-balls/main/doas.tar.gz 
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  218k  100  218k    0     0   610k      0 --:--:-- --:--:-- --:--:--  610k
cc -Wall -O2 -DUSE_PAM -DDOAS_CONF=\"/usr/local/etc/doas.conf\"  -D_GNU_SOURCE -include compat/compat.h -Icompat  -c -o doas.o doas.c
doas.c:48:10: fatal error: security/pam_appl.h: Datei oder Verzeichnis nicht gefunden
   48 | #include <security/pam_appl.h>
      |          ^~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make: *** [<eingebaut>: doas.o] Fehler 1
cc -Wall -O2 -DUSE_PAM -DDOAS_CONF=\"/usr/local/etc/doas.conf\"  -D_GNU_SOURCE -include compat/compat.h -Icompat  -c -o doas.o doas.c
doas.c:48:10: fatal error: security/pam_appl.h: Datei oder Verzeichnis nicht gefunden
   48 | #include <security/pam_appl.h>
      |          ^~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make: *** [<eingebaut>: doas.o] Fehler 1
2021/09/23 15:07:58 exit status 2
moritz@pop-os:~$

**Comment by luis-07** [comment]
That’s a problem with your distro you don’t have the need c library’s installed

**Comment by Moritz448** [comment]
Looking like a error from doas

**Comment by Moritz448** [comment]
So you comment always 2 seconds before i press send :D

**Comment by luis-07** [comment]
I have to go I’ll back in 1:30 h I have to learn some vocabularies.

**Comment by Moritz448** [comment]
Me too ;=)

**Comment by luis-07** [comment]
Now i start implementing the new repo system
