### ISSUE TITLE
Add more insults against the user

### ISSUE THREAD

**Issue by Moritz448** [luis-07/gpac#13]
We should add more insults because we are lost.

**Comment by Moritz448** [comment]
Implemented in kind of a way

**Comment by luis-07** [comment]
no

**Comment by luis-07** [comment]
no output at the moment

**Comment by Moritz448** [comment]
Its implemented in my version and in the old so i would say close it

**Comment by luis-07** [comment]
not compatible anymore

**Comment by luis-07** [comment]
it`s called rewrite because i changed everyting

**Comment by Moritz448** [comment]
Implemented
