### ISSUE TITLE
Rewrite 

### ISSUE THREAD

**Issue by luis-07** [luis-07/gpac#15]
I’ll rewrite the hole thing in clean code and add many features requested. At the moment the code for the rewrite it und dev/rewrite.go. I do this because:
I want a cleaner codebase and a new repo system

**Comment by Moritz448** [comment]
Could you please use a seperate branch? That's what git is designed for so i can test and do other things in parallel.

**Comment by luis-07** [comment]
Yes but probably the next commit is the final version

**Comment by Moritz448** [comment]
Could we write in the Discussions tab? Thats much easier, i started a german channel

**Comment by Moritz448** [comment]
First question: Do you add a /src dir, so i can delete the issue?
Second: Do you add dependencies so i can close this?

**Comment by luis-07** [comment]
Yes I’ll add them but close them when I added them maybe I decide to not add one of this features because it is to difficult or something like this.

**Comment by luis-07** [comment]
@Moritz448 can you call me?

**Comment by Moritz448** [comment]
So i close this now because the new code base is implemented

**Comment by luis-07** [comment]
ok can you talk

**Comment by luis-07** [comment]
@Moritz448
