### ISSUE TITLE
[FEATURE SUGGESTION] Sub Repos

### ISSUE THREAD

**Issue by Moritz448** [luis-07/gpac#18]
**Is your feature request related to a problem? Please describe.**
At the time we are we couldn´t use sub repos or custom user repos. We should change that.

**Describe the solution you´d like**
I would say we do it as @luis-07 mentioned it with folders so you can acess them with /.

**Describe alternatives you´ve considered**
I think, a possible alternative could be to use the first package the program finds, so if cowsay is in the main repo and in a custom repo, it uses the one from the main repo

**Comment by luis-07** [comment]
not high priotiy

**Comment by Moritz448** [comment]
But easy to implement

**Comment by luis-07** [comment]
nope

**Comment by luis-07** [comment]
wait it`s way to easy

**Comment by luis-07** [comment]
i`ll push it in a few

**Comment by Moritz448** [comment]
Ok and as you can see i´ve added it to the .2 milestone so not so high priority

**Comment by luis-07** [comment]
it kind of works i go sleep now

**Comment by luis-07** [comment]
DONE!!!!!
