### ISSUE TITLE
[FEATURE SUGGESTION]  install gpac with gpac

### ISSUE THREAD

**Issue by luis-07** [luis-07/gpac#23]

**Comment by Moritz448** [comment]
This could be a very useful feature

**Comment by Moritz448** [comment]
But it could end in a endless recursion

**Comment by luis-07** [comment]
Think first than say something

**Comment by luis-07** [comment]
DONE !!(just on my local fork but done)

**Comment by luis-07** [comment]
Oh no I distrohopped to openbsd.
Guess who doesn't have a backup

**Comment by luis-07** [comment]
fixed with update script
