### ISSUE TITLE
[FEATURE SUGGESTION] Better Documentation

### ISSUE THREAD

**Issue by Moritz448** [luis-07/gpac#26]
**Is your feature request related to a problem? Please describe.**
If I want to use gPac, I don´t know how to use it because the Documentation is fucking shit.

**Describe the solution you'd like**
I would recommend writing a clear and useful Documentation.
**Describe alternatives you've considered**
A possible alternative is to don´t write a Documentation and try to use it without because this sucks less for us as Project maintainers.

**Comment by luis-07** [comment]
ask me every question you have in this issue and write the documentation yourself
