### ISSUE TITLE
[BUG] FIX SUBMODULE SHIT

### ISSUE THREAD

**Issue by luis-07** [luis-07/gpac#41]
nobody likes submodules and vscode

**Comment by Moritz448** [comment]
What the fuck should i do? Remove the submodule and create a directory for the wiki?

**Comment by luis-07** [comment]
I did it for you you have to package the packages you fucked up

**Comment by luis-07** [comment]
I send you a link on WhatsApp

**Comment by luis-07** [comment]
https://github.com/luis-07/gpac-main-repo/invitations

**Comment by luis-07** [comment]
and man don't commit shit before it is fixed because I don't want to spend the rest of my life with reading the email I get every time a check fails which is annoying as fuck.
